# Generated by Django 4.1.5 on 2023-01-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LOGIN_CONTROL_TABLE',
            fields=[
                ('ip', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
        ),
        migrations.CreateModel(
            name='PUSH_HISTORY_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('alias', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=255)),
                ('toasted_datetime', models.TimeField()),
                ('repeat', models.BooleanField()),
                ('ad', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SCHEDULED_PUSH_TABLE',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('alias', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField()),
                ('repeat', models.BooleanField()),
                ('ad', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SYSTEM_LOG_TABLE',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=0, max_digits=1)),
                ('application_name', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TARGET_TABLE',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=20)),
                ('device_type', models.CharField(max_length=8)),
                ('is_push_allow', models.BooleanField()),
                ('is_ad_allow', models.BooleanField()),
                ('is_night_allow', models.BooleanField()),
                ('last_active_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='USER_EMAIL_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='USER_TABLE',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=8)),
                ('application_icon', models.ImageField(upload_to='application_icons')),
                ('application_name', models.CharField(max_length=64)),
                ('tel', models.CharField(max_length=64)),
                ('service_id', models.CharField(max_length=255)),
                ('access_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('expire_date', models.DateField()),
            ],
        ),
    ]
