# Generated by Django 4.1.5 on 2023-02-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASSIGNED_TARGET_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_id', models.CharField(max_length=20)),
                ('target_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LOGIN_CONTROL_TABLE',
            fields=[
                ('ip', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
        ),
        migrations.CreateModel(
            name='PUSH_HISTORY_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toaster_id', models.CharField(max_length=20)),
                ('alias', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=255)),
                ('toasted_datetime', models.DateTimeField()),
                ('repeat', models.BooleanField()),
                ('ad', models.BooleanField()),
                ('count', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SCHEDULED_PUSH_TABLE',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('toaster_id', models.CharField(max_length=20)),
                ('alias', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField()),
                ('repeat', models.BooleanField()),
                ('ad', models.BooleanField()),
                ('target_assign', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SYSTEM_LOG_TABLE',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=0, max_digits=1)),
                ('application_name', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TARGET_TABLE',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('toaster_id', models.CharField(max_length=20)),
                ('device_type', models.CharField(max_length=8)),
                ('is_push_allow', models.BooleanField()),
                ('push_allow_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_ad_allow', models.BooleanField()),
                ('ad_allow_datetime', models.DateTimeField(blank=True, null=True)),
                ('last_active_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TOASTER_TABLE',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('application_icon', models.ImageField(upload_to='icons')),
                ('application_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('tel', models.CharField(max_length=64)),
                ('app_admin_key', models.CharField(max_length=255)),
                ('create_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('is_push', models.BooleanField()),
            ],
        ),
    ]
