# Generated by Django 4.1.7 on 2023-03-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrated', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOGGER_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=100)),
            ],
        ),
    ]
