# Generated by Django 4.1.5 on 2023-02-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrated', '0002_timer_alter_login_try_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_table',
            name='user_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_table',
            name='layout_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='theme',
            field=models.CharField(max_length=20),
        ),
    ]
